### ISSUE TITLE
SAM build fails on 'npm prune'

### ISSUE THREAD

**Issue by josep11** [aws/aws-lambda-builders#304]
### Description:
I am using a custom Makefile to copy only some artifacts to the .aws-sam folder and to perform some tasks.
I am running `sam build` and it seems that there is a permission problem with `npm prune --production` when it tries to remove the unnecessary npm dev packages.

If I run `npm prune --production` from the terminal it works perfectly.

### Steps to reproduce:

Have a node.js with some npm dependencies, src, config folders and handler.js on the root

This is the Makefile:
```
build-RssFetchNewJobs:
	npm install
	npm test
	npm prune --production
ifeq ($(OS),Windows_NT)
	Xcopy /E * $(ARTIFACTS_DIR) 
else
	cp -r handler.js src node_modules config $(ARTIFACTS_DIR)
endif
```

Even being a really bad practice I changed the conflicting line with `sudo npm prune --production` and it run without problems.

### Observed result:

If the modules to be removed are installed using `sam` command (in the build) then everything works properly, but if they were installed by my OS user (straight from the terminal) then it doesn't work. The output is:

> Build Failed
> Error: CustomMakeBuilder:MakeBuild - Make Failed: internal/modules/cjs/loader.js:968
>   throw err;
>   ^
> 
> Error: Cannot find module '../lib/cli/options'
> Require stack:
> - /private/var/folders/ck/r6n33qs13zx7j2w3trsnvl6c0000gn/T/tmp6gklk5wn/node_modules/.bin/mocha
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/private/var/folders/ck/r6n33qs13zx7j2w3trsnvl6c0000gn/T/tmp6gklk5wn/node_modules/.bin/mocha:13:23)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/private/var/folders/ck/r6n33qs13zx7j2w3trsnvl6c0000gn/T/tmp6gklk5wn/node_modules/.bin/mocha'
>   ]
> }
> npm ERR! Test failed.  See above for more details.
> make: *** [build-RssFetchNewJobs] Error 1

### Expected result:
the folders under node_modules to be deleted by `sam`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 10.14.6
2. `sam --version`: 1.31.0
3. AWS region: eu-west-3

Those are my dependencies in package.json:
```json
"dependencies": {
    "axios": "^0.23.0",
    "dotenv": "^10.0.0",
    "fast-xml-parser": "^3.20.3",
    "fs": "0.0.1-security",
    "luxon": "^2.0.2"
  },
  "devDependencies": {
    "chai": "^4.3.4",
    "eslint": "^8.0.0",
    "mocha": "^9.1.2",
    "mocha-junit-reporter": "^2.0.2"
  }
```

**Comment by mndeveci** [comment]
@josep11 looking at the problem, it seems like it is caused by relative symlinks. Is there  a way to generate those symlinks with absolute path, which should work on the same machine?

**Comment by lucashuy** [comment]
Thanks for creating this issue. Closing due to inactivity, please feel free to reopen this issue if there are any findings or create a new issue if you have any other feedback.
